name: ai_tryon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
